const testimonialContent = {
  heading: "What Traders Say About ALGODER",
  subheading: "Real feedback from customers using our algos and trading tools daily.",
  testimonials: [
    {
      name: "Rohit Malhotra",
      role: "Algo Trader, Mumbai",
      image: "/avatars/avatar1.jpg",
      rating: 5,
      message: "ALGODER’s Excel tools are super accurate and save me hours every day. The delivery was instant and setup was very easy!",
    },
    {
      name: "Neha Verma",
      role: "Retail Investor, Delhi",
      image: "/avatars/avatar2.jpg",
      rating: 4,
      message: "As someone with no coding background, I found their readymade algos very helpful. Customer support helped me configure everything.",
    },
    {
      name: "Suresh Patel",
      role: "Full-time Trader, Ahmedabad",
      image: "/avatars/avatar3.jpg",
      rating: 5,
      message: "I bought an option chain analyzer and it works flawlessly! I’ve already recommended ALGODER to my trading group.",
    },
    {
      name: "Aman Srivastava",
      role: "Intraday Trader, Lucknow",
      image: "/avatars/avatar4.jpg",
      rating: 5,
      message: "Bro tool mast bana hai! SL aur target dono auto set ho jaate hain. Bilkul tension-free trading ho rahi hai.",
    },
    {
      name: "Pooja Shah",
      role: "Beginner Trader, Pune",
      image: "/avatars/avatar5.jpg",
      rating: 4,
      message: "I was totally new to algo trading but ALGODER's team explained everything step-by-step. Now I place trades confidently.",
    },
    {
      name: "Rajiv Mehta",
      role: "Bank Nifty Trader, Jaipur",
      image: "/avatars/avatar6.jpg",
      rating: 5,
      message: "Algo speed is solid. Excel tool ne manual kaam half kar diya. Definitely paisa vasool.",
    },
    {
      name: "Priya Dey",
      role: "Part-time Trader, Kolkata",
      image: "/avatars/avatar7.jpg",
      rating: 4,
      message: "Mujhe option buying ke liye strategy chahiye thi, yaha mujhe ready-to-use algo mil gaya. Thanks ALGODER!",
    },
    {
      name: "Ishaan Khanna",
      role: "Swing Trader, Chandigarh",
      image: "/avatars/avatar8.jpg",
      rating: 5,
      message: "Their backtesting feature is 🔥. Helped me fine-tune my Bank Nifty strategy with real data insights.",
    },
    {
      name: "Deepika Sharma",
      role: "Equity Investor, Noida",
      image: "/avatars/avatar9.jpg",
      rating: 5,
      message: "Earlier I used to depend on tips, but after using ALGODER’s algo tools, I understand the logic behind each trade.",
    },
    {
      name: "Ramesh Bhatt",
      role: "Commodity Trader, Indore",
      image: "/avatars/avatar10.jpg",
      rating: 4,
      message: "Zerodha ke liye algo chahiye tha, yaha mil gaya pre-configured. Setup mein bhi help mili instantly.",
    },
    {
      name: "Tanvi Patel",
      role: "Option Writer, Surat",
      image: "/avatars/avatar11.jpg",
      rating: 5,
      message: "Option chain tool is next-level. Strike selection karne mein ab bilkul dikkat nahi hoti.",
    },
    {
      name: "Yash Jain",
      role: "Scalper, Bengaluru",
      image: "/avatars/avatar12.jpg",
      rating: 5,
      message: "Latency kam hai, orders fast lagte hain. Just plug and play, kaafi simple system hai.",
    },
    {
      name: "Meena Rathore",
      role: "Housewife & Trader, Bhopal",
      image: "/avatars/avatar13.jpg",
      rating: 4,
      message: "Main coding nahi janti hoon par ALGODER ka system easy to use hai. Mujhe daily profit mil raha hai.",
    },
    {
      name: "Naveen Kumar",
      role: "Options Trader, Hyderabad",
      image: "/avatars/avatar14.jpg",
      rating: 5,
      message: "Telegram par jab dekha to laga fake hoga, par jab try kiya to tool ne kamaal kar diya. 👏",
    },
    {
      name: "Farah Qureshi",
      role: "Tech Analyst, Delhi",
      image: "/avatars/avatar15.jpg",
      rating: 5,
      message: "Loved the clean UI and customer support. I had so many doubts, and they were all resolved quickly.",
    },
    {
      name: "Tushar Rawat",
      role: "Manual to Algo Shifted, Dehradun",
      image: "/avatars/avatar16.jpg",
      rating: 5,
      message: "Pehle sab manually karta tha, ab ALGODER ke saath automate kar diya. Losses bhi kam hue aur time bhi bacha.",
    },
    {
      name: "Kiran Joshi",
      role: "College Student, Nagpur",
      image: "/avatars/avatar17.jpg",
      rating: 4,
      message: "Main side hustle ke liye algo use kar raha hoon, working perfect so far. Pocket-friendly bhi hai.",
    },
    {
      name: "Mohammed Faisal",
      role: "Day Trader, Chennai",
      image: "/avatars/avatar18.jpg",
      rating: 5,
      message: "Dashboard clean hai aur tools responsive hain. Itna sasta aur effective tool pehli baar dekha.",
    },
    {
      name: "Anjali Thakur",
      role: "Part-time Trader, Ranchi",
      image: "/avatars/avatar19.jpg",
      rating: 5,
      message: "Amazing experience! Telegram support quick tha, aur mujhe strategy bhi samjha di detail mein.",
    },
    {
      name: "Siddharth Iyer",
      role: "Engineer + Trader, Kochi",
      image: "/avatars/avatar20.jpg",
      rating: 5,
      message: "Coding background se hoon, but ALGODER ki premade strategies bohot smartly banaayi gayi hain. I’m impressed.",
    },
  ],
};

export default testimonialContent;
