# Generated by Django 5.2.1 on 2026-08-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url_2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
