# Generated by Django 5.2.1 on 2025-05-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0002_product_image1_product_image2_product_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='homepage',
            field=models.BooleanField(default=False),
        ),
    ]
