# Generated by Django 5.2.1 on 2026-08-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0002_product_video_url_1_product_video_url_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
