# Generated by Django 5.2.1 on 2025-05-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0005_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Getfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='products/')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='file',
        ),
    ]
