# Generated by Django 5.2.1 on 2026-08-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0006_alter_order_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteVisit',
        ),
    ]
