# Generated by Django 5.2.1 on 2025-05-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0006_getfile_remove_product_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='products/'),
        ),
    ]
