# Generated by Django 5.2.1 on 2025-06-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0010_topic_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(default='', upload_to='course_videos/'),
            preserve_default=False,
        ),
    ]
