# Generated by Django 5.2.1 on 2025-06-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0011_remove_video_url_video_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
