# Generated by Django 5.2.1 on 2025-06-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0012_remove_video_video_file_video_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='documentation',
            field=models.JSONField(default=dict),
        ),
    ]
