# Generated by Django 5.2.1 on 2025-06-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0013_video_documentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_percent', models.PositiveIntegerField()),
                ('video_url', models.URLField(help_text='Course intro video (YouTube embed URL)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/')),
                ('features', models.TextField(help_text='Bullet points separated by newline')),
                ('learning_objectives', models.TextField(help_text="What you'll learn")),
                ('requirements', models.TextField(help_text='Prerequisites')),
                ('target_audience', models.TextField(help_text='Who this course is for')),
                ('full_description', models.TextField()),
                ('curriculum', models.TextField(help_text='One line per topic/module')),
                ('instructor_name', models.CharField(max_length=100)),
                ('instructor_bio', models.TextField()),
                ('instructor_image', models.ImageField(blank=True, null=True, upload_to='instructors/')),
                ('language', models.CharField(default='English', max_length=50)),
                ('level', models.CharField(default='Beginner', max_length=50)),
                ('duration', models.CharField(default='6 hours', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
