# Generated by Django 5.2.1 on 2025-06-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0014_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='types',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='types',
            field=models.TextField(blank=True),
        ),
    ]
