# Generated by Django 5.2.1 on 2025-06-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0015_course_types_product_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='types',
            field=models.TextField(blank=True),
        ),
    ]
